"""
Unit tests for api_tool.analyzer.graphql_parser.GraphQLQueryExtractor.

Tests:
1. Tagged template literals (Apollo gql, Relay graphql, urql, graphql-request)
2. Commented strings (/* GraphQL */ and #graphql)
3. Precompiled AST objects (TypedDocumentNode, @graphql-codegen/client-preset)
4. Relay ConcreteRequest objects (both text-based and persisted with null text)
5. graphql-core validation, operation type detection, variable sample generation
6. Resilient regex fallback on broken syntax without crashing
7. Candidate GraphQL endpoint detection (Apollo, urql, fetch, standard paths)
"""

import unittest
from api_tool.analyzer.graphql_parser import GraphQLQueryExtractor
from api_tool.models import GraphQLOperation


class TestGraphQLQueryExtractor(unittest.TestCase):
    def setUp(self):
        self.extractor = GraphQLQueryExtractor()

    def test_extract_apollo_gql_tagged_template(self):
        code = """
        import { gql } from '@apollo/client';

        export const GET_USER_PROFILE = gql`
          query GetUserProfile($id: ID!, $limit: Int = 10) {
            user(id: $id) {
              id
              name
              email
            }
          }
        `;
        """
        ops = self.extractor.extract_from_code(code)
        self.assertEqual(len(ops), 1)
        op = ops[0]
        self.assertIsInstance(op, GraphQLOperation)
        self.assertEqual(op.operation_type, "query")
        self.assertEqual(op.operation_name, "GetUserProfile")
        self.assertEqual(op.endpoint, "/graphql")
        self.assertIn("user(id: $id)", op.query_string)
        self.assertIsNotNone(op.variables_sample)
        self.assertEqual(op.variables_sample["id"], "1")
        self.assertEqual(op.variables_sample["limit"], 10)

    def test_extract_relay_graphql_mutation(self):
        code = """
        import { graphql } from 'react-relay';

        const UpdateUser = graphql`
          mutation UpdateUserMutation($input: UpdateUserInput!) {
            updateUser(input: $input) {
              user {
                id
                name
              }
            }
          }
        `;
        """
        ops = self.extractor.extract_from_code(code)
        self.assertEqual(len(ops), 1)
        op = ops[0]
        self.assertEqual(op.operation_type, "mutation")
        self.assertEqual(op.operation_name, "UpdateUserMutation")
        self.assertIn("updateUser", op.query_string)
        self.assertIn("input", op.variables_sample)

    def test_extract_commented_strings(self):
        code = """
        // 1. /* GraphQL */ template literal
        const LIST_POSTS = /* GraphQL */ `
          query ListPosts($first: Int = 20) {
            posts(first: $first) {
              id
              title
            }
          }
        `;

        // 2. #graphql inline comment
        const SUBSCRIPTION = `
          #graphql
          subscription OnCommentAdded($postId: ID!) {
            commentAdded(postId: $postId) {
              id
              content
            }
          }
        `;

        // 3. /* GraphQL */ quoted string
        const GET_STATUS = /* GraphQL */ "query GetStatus { status }";
        """
        ops = self.extractor.extract_from_code(code)
        self.assertEqual(len(ops), 3)

        op_names = {op.operation_name: op for op in ops}
        self.assertIn("ListPosts", op_names)
        self.assertIn("OnCommentAdded", op_names)
        self.assertIn("GetStatus", op_names)

        self.assertEqual(op_names["ListPosts"].operation_type, "query")
        self.assertEqual(op_names["OnCommentAdded"].operation_type, "subscription")
        self.assertEqual(op_names["GetStatus"].operation_type, "query")

    def test_extract_precompiled_typed_document_node(self):
        # Compiled TypedDocumentNode as generated by @graphql-codegen/client-preset
        code = """
        export const HelloDocument = {
          kind: "Document",
          definitions: [
            {
              kind: "OperationDefinition",
              operation: "query",
              name: { kind: "Name", value: "Hello" },
              variableDefinitions: [
                {
                  kind: "VariableDefinition",
                  variable: { kind: "Variable", name: { kind: "Name", value: "limit" } },
                  type: { kind: "NamedType", name: { kind: "Name", value: "Int" } },
                  defaultValue: { kind: "IntValue", value: "5" }
                }
              ],
              selectionSet: {
                kind: "SelectionSet",
                selections: [
                  {
                    kind: "Field",
                    name: { kind: "Name", value: "hello" },
                    arguments: [
                      {
                        kind: "Argument",
                        name: { kind: "Name", value: "limit" },
                        value: { kind: "Variable", name: { kind: "Name", value: "limit" } }
                      }
                    ]
                  }
                ]
              }
            }
          ]
        };
        """
        ops = self.extractor.extract_from_code(code)
        self.assertEqual(len(ops), 1)
        op = ops[0]
        self.assertEqual(op.operation_type, "query")
        self.assertEqual(op.operation_name, "Hello")
        self.assertIn("hello(limit: $limit)", op.query_string)
        self.assertEqual(op.variables_sample, {"limit": 5})

    def test_extract_relay_concrete_request_standard(self):
        code = """
        const node = {
          "kind": "Request",
          "fragment": {
            "argumentDefinitions": [],
            "kind": "Fragment",
            "name": "TodoItemRefetchQuery",
            "selections": [
              {
                "alias": null,
                "args": null,
                "kind": "ScalarField",
                "name": "id",
                "storageKey": null
              }
            ],
            "type": "Query"
          },
          "operation": {
            "argumentDefinitions": [],
            "kind": "Operation",
            "name": "TodoItemRefetchQuery"
          },
          "params": {
            "cacheID": "abcdef123456",
            "id": null,
            "metadata": {},
            "name": "TodoItemRefetchQuery",
            "operationKind": "query",
            "text": "query TodoItemRefetchQuery($itemID: ID!) {\\n  node(id: $itemID) {\\n    id\\n  }\\n}\\n"
          }
        };
        """
        ops = self.extractor.extract_from_code(code)
        self.assertEqual(len(ops), 1)
        op = ops[0]
        self.assertEqual(op.operation_type, "query")
        self.assertEqual(op.operation_name, "TodoItemRefetchQuery")
        self.assertIn("node(id: $itemID)", op.query_string)
        self.assertEqual(op.variables_sample, {"itemID": "1"})

    def test_extract_relay_concrete_request_persisted(self):
        # In persisted queries, text is null and ID is present
        code = """
        const node = {
          kind: "Request",
          fragment: {
            kind: "Fragment",
            name: "TodoItemPersistedQuery",
            selections: [
              {
                kind: "LinkedField",
                name: "node",
                args: [{ kind: "Variable", name: "id", variableName: "itemID" }],
                selections: [
                  { kind: "ScalarField", name: "id" }
                ]
              }
            ]
          },
          operation: {
            kind: "Operation",
            name: "TodoItemPersistedQuery",
            argumentDefinitions: [{ name: "itemID", type: "ID!" }]
          },
          params: {
            cacheID: "hash123",
            id: "3be4abb81fa595e25eb725b2c6a87508",
            name: "TodoItemPersistedQuery",
            operationKind: "query",
            text: null
          }
        };
        """
        ops = self.extractor.extract_from_code(code)
        self.assertEqual(len(ops), 1)
        op = ops[0]
        self.assertEqual(op.operation_type, "query")
        self.assertEqual(op.operation_name, "TodoItemPersistedQuery")
        self.assertIn("node", op.query_string)
        self.assertEqual(op.variables_sample, {"itemID": "1"})

    def test_resilient_regex_fallback_on_broken_syntax(self):
        # A query with invalid/broken template interpolation that fails graphql-core AST parse
        code = """
        const BROKEN_QUERY = gql`
          query BrokenFeedQuery($userId: ID!, $count: Int = 15) {
            feed(user: $userId) {
              ${someDynamicValue ? 'broken_field' : 'other_field'}
              unclosed_brace: {
        `;
        """
        ops = self.extractor.extract_from_code(code)
        self.assertEqual(len(ops), 1)
        op = ops[0]
        self.assertEqual(op.operation_type, "query")
        self.assertEqual(op.operation_name, "BrokenFeedQuery")
        self.assertIn("userId", op.variables_sample)
        self.assertEqual(op.variables_sample["count"], 15)

    def test_detect_graphql_endpoints(self):
        code = """
        import { ApolloClient, InMemoryCache, createHttpLink } from '@apollo/client';
        import { createClient } from 'urql';
        import { GraphQLClient, request } from 'graphql-request';

        const link = createHttpLink({ uri: 'https://backend.example.com/api/graphql' });
        const client = new ApolloClient({ link, cache: new InMemoryCache() });

        const urql = createClient({
          url: '/api/v1/graphql',
        });

        const directClient = new GraphQLClient('https://content.api.com/graphql');
        const simpleReq = request('/query', '{ ping }');

        const fetchRes = await fetch('/graphql', { method: 'POST', body: JSON.stringify({ query: '{ me }' }) });

        const envUri = process.env.NEXT_PUBLIC_GRAPHQL_ENDPOINT || '/api/graphql';
        """
        endpoints = self.extractor.detect_graphql_endpoints(code)
        expected_endpoints = [
            "https://backend.example.com/api/graphql",
            "/api/v1/graphql",
            "https://content.api.com/graphql",
            "/query",
            "/graphql",
            "/api/graphql",
        ]
        for ep in expected_endpoints:
            self.assertIn(ep, endpoints)

    def test_endpoint_applied_to_extracted_operations(self):
        code = """
        const client = new ApolloClient({ uri: 'https://api.github.com/graphql' });
        const VIEWER_QUERY = gql`
          query ViewerQuery {
            viewer {
              login
            }
          }
        `;
        """
        ops = self.extractor.extract_from_code(code)
        self.assertEqual(len(ops), 1)
        self.assertEqual(ops[0].endpoint, "https://api.github.com/graphql")

    def test_custom_default_endpoint_override(self):
        code = """
        const VIEWER_QUERY = gql`
          query ViewerQuery {
            viewer {
              login
            }
          }
        `;
        """
        ops = self.extractor.extract_from_code(code, default_endpoint="/custom/graphql")
        self.assertEqual(len(ops), 1)
        self.assertEqual(ops[0].endpoint, "/custom/graphql")

    def test_anonymous_query_handling(self):
        code = """
        const SIMPLE_QUERY = gql`
          {
            users {
              id
              name
            }
          }
        `;
        """
        ops = self.extractor.extract_from_code(code)
        self.assertEqual(len(ops), 1)
        self.assertEqual(ops[0].operation_type, "query")
        self.assertEqual(ops[0].operation_name, "anonymous")

    def test_query_with_fragment_inclusion(self):
        code = """
        const GET_USER_WITH_FRAGMENT = gql`
          query GetUserWithFrag($id: ID!) {
            user(id: $id) {
              ...UserFields
            }
          }

          fragment UserFields on User {
            id
            username
            email
          }
        `;
        """
        ops = self.extractor.extract_from_code(code)
        self.assertEqual(len(ops), 1)
        op = ops[0]
        self.assertEqual(op.operation_name, "GetUserWithFrag")
        # Fragment definition must be included in query_string so it's standalone executable
        self.assertIn("fragment UserFields on User", op.query_string)
        self.assertIn("...UserFields", op.query_string)


if __name__ == "__main__":
    unittest.main()
